### ISSUE TITLE
"Index was outside the bounds of the array."

### ISSUE THREAD

**Issue by TwanVanDongen** [spkl/Diffs#6]
on line 71 in public class VArray<T> I get the "Index was outside the bounds of the array." whilst comparing two files:

[TMP.ZIP](https://github.com/spkl/Diffs/files/6249445/TMP.ZIP)

thanks in advance for fixing!

**Comment by spkl** [comment]
Code to reproduce:
```
var a = File.ReadAllBytes(@"D54ACE32535F00233F43B243D0EF1EDE.mus");
var b = File.ReadAllBytes(@"Smooth_Operator.mus");
var d = new MyersDiff<int>(a, b);
```

**Comment by spkl** [comment]
@TwanVanDongen Thank you for reporting this, it was a serious issue.
